# Generated by Django 3.1.2 on 2021-08-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210823_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('commenter_name', models.CharField(max_length=19)),
                ('commenter_username', models.CharField(max_length=19, null=True)),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment_id', models.IntegerField(default=-1)),
                ('post_author_name', models.CharField(max_length=99, null=True)),
            ],
        ),
    ]
