# Generated by Django 3.1.2 on 2021-08-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commenter_username',
            field=models.CharField(default='nothing', max_length=19),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_author_name',
            field=models.CharField(max_length=99),
        ),
    ]
