# Generated by Django 3.1.2 on 2021-08-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_post_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=19)),
                ('phone', models.CharField(max_length=19)),
                ('village', models.CharField(max_length=19)),
                ('word', models.DateTimeField(auto_now_add=True)),
                ('complain', models.IntegerField(default=-1)),
            ],
        ),
    ]
