# Generated by Django 3.1.2 on 2021-08-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210826_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='next_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=19)),
                ('project', models.CharField(max_length=9000)),
            ],
        ),
    ]
