# Generated by Django 3.1.2 on 2021-08-27 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_next_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='next_project',
            name='name',
        ),
    ]
